### ISSUE TITLE
Use without any material dependency?

### ISSUE THREAD

**Issue by calvintam236** [adrianos42/desktop#1]
Hey @adrianos42,

I am using this package to build a web app based on Flutter, and I have some questions regarding theming the components. The few I have used so far do not include passing `decoration` and I had to use a `Container()` wrapping it for background. Is it possible to make all components to use without `Theme` and `ThemeData` (from `material` library), such as adding decoration as parameter?

Thanks.

**Comment by adrianos42** [comment]
Which components exactly are you using? At the moment, the only one I am considering using background as parameter is `Nav`. Unfortunately, `Theme` and `ThemeData` are also defined with the same names in the library, so you need to either import one the libraries with `as`, or import each component using `show` from dart. If it's an issue to have `Theme` and `ThemeData` with the same names used in the material library, then I might change it later.

**Comment by calvintam236** [comment]
I’m using TextField and Checkbox for a form. I would like to custom the `decoration` individually instead of using theme. Right now, I don’t see a way to do that without `Theme` or `ThemeData`.

My web app is using `WidgetsApp`, not `MaterialApp`. There is no `theme` in the `context`.

**Comment by adrianos42** [comment]
I recommend you to either use `DesktopApp`, but if you need to use `WidgetsApp directly, see how the `DesktopApp` class works, since it uses `WidgetsApp` and the `Theme` context as children. This because many components depend on `ThemeData` to work, so you would need at least to use `Theme` as a child in `WidgetsApp`. Also, I still need to fix some code for `TextField`, and I was already going to create a parameter for decoration, since cupertino and material libraries also have the option to include a decoration for the box around the text. But I still need to implement it.

**Comment by calvintam236** [comment]
I started my app without `desktop` at the beginning, and chose to use `WidgetsApp` at that time. I am not aware there is `DesktopApp` in `desktop` (not mentioned in the README). However, looking at the code, do you have the `.router()` constructor for `DesktopApp` (seems like there is no equivalent of `WidgetApp.router()`)? I am using `beamer` package for navigating between pages and not sure how to use with `DesktopApp`.

**Comment by adrianos42** [comment]
Are you using this library as a git dependency or from pub? I will implement the `router` constructor for `DesktopApp`, and if necessary I will create another version on pub.dev.

**Comment by calvintam236** [comment]
I am using `beamer` from pub. I think you can just add `.router()` in the existing repo should work, right?

**Comment by adrianos42** [comment]
I meant `desktop`, if you are using direct from this repo, or from pub. But anyways, I'm gonna do some tests using `beam`, and see if everything works fine. Then I will publish the new version in pub.

**Comment by calvintam236** [comment]
Oh. I am using `desktop` from pub as well.

**Comment by adrianos42** [comment]
I've publish desktop 2.0.0 in pub.dev. There's now the 'router' constructor and I also added the decoration field for `TextField`. It should allow you to change the box decoration. I needed to change some stuff, but mostly for `Nav` and `Tab` classes, that I still needed to fix some issues, so maybe a few break changes. If you have any problem with routes while using `beam`, please then create another issue.

**Comment by adrianos42** [comment]
Are you having any problem with using routes? I think there might be some problems with `Nav` widget, are you using it?

**Comment by calvintam236** [comment]
Planning to upgrade my old code (just a `GestureDetector`) to the `Nav`, but I haven’t started yet.

One of my teammate tried to use the `Tab` (v1.0.4 at that time), but clicking on the Tab does not work. It is not switching to another tab’s content.

**Comment by calvintam236** [comment]
I am trying to migrate the code, but the way I was using is `GestureDetector` with `onTap` calling `context.beamToNamed(this.route)`.

When I am looking at your code, `NavItem` requires all `builder`, `title`, `route`, and `icon`. My nav does not use an icon (text only), and I want to just beam to another page (or do custom function). Any chance this `NavItem` can accept just `title` and `onPressed()`?
