### ISSUE TITLE
DropdownButton color 

### ISSUE THREAD

**Issue by NafissaBHJ** [adrianos42/desktop#15]
Hello,
I'm using the dropdownButton widget  it's good but I can't change the background color as it appears black, I tried to wrap it withe the dropdownButtonTheme but nothing changed. Am I  missing anything ?

**Comment by adrianos42** [comment]
Do you want to change the background of the button or the item? If you wanna only change `ContextMenuItem`, you can use a `ContextMenuTheme`. As for changing the button background itself, I'm working to allow changing the background when the button is focused or inactive.

**Comment by adrianos42** [comment]
You can now use the `ContextMenuTheme` to change the menu background, or `DropDownButtonTheme` to change the button background.
