### ISSUE TITLE
[FR] [ListTable] drag the header to resort the column

### ISSUE THREAD

**Issue by leedstyh** [adrianos42/desktop#18]
Hi, is this feature on the plan?

**Comment by adrianos42** [comment]
Do you mean dragging the entire column and changing its position?

**Comment by leedstyh** [comment]
yes @adrianos42

**Comment by adrianos42** [comment]
Yes, I will implement it. This will be in the next version of the library. But I still need to fix some other stuff.

**Comment by leedstyh** [comment]
Good to know, thanks @adrianos42
