### ISSUE TITLE
On flutter 3.0, I recived some warning msg

### ISSUE THREAD

**Issue by ZJiSong** [adrianos42/desktop#19]
/D:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/desktop-3.1.5/lib/src/desktop/scrolling/scrollbar.dart:445:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((Duration duration) {
                   ^
/D:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/desktop-3.1.5/lib/src/desktop/input/button.dart:325:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.pointerRouter.addGlobalRoute(_mouseRoute);

**Comment by adrianos42** [comment]
This is because the current version depends on the older dart sdk version. Shouldn't be an issue.
