### ISSUE TITLE
Put a [TextField]/[TextFormField] inside [ListTable] cell throws 'Bad State' error

### ISSUE THREAD

**Issue by marcoredz** [adrianos42/desktop#23]
### Code example
Take the [list table example](https://github.com/adrianos42/desktop/blob/master/docs_web/lib/data/list_table.dart) 
and put a TextField widget as cell
```
rows: List.generate(10, (row) {
  return ListTableRow(
    builder: (context, col) => Container(
      alignment: Alignment.centerLeft,
      padding: const EdgeInsets.symmetric(horizontal: 8.0),
      child: TextField(key: Key('$row$col'))
    ),
  );
}),
```

I get the error:

> ════════ Exception caught by rendering library ═════════════════════════════════
> The following StateError was thrown during paint():
> Bad state: A Dart object attempted to access a native peer, but the native peer has been collected (nullptr). This is usually the result of calling methods on a native-backed object when the native resources have already been disposed.

Looking at the stack, the error seems to be generated from [ListRowRenderer](https://github.com/adrianos42/desktop/blob/master/desktop/lib/src/desktop/data/list_table/list_row.dart) at line 350

**Comment by adrianos42** [comment]
Can you see if it works now? I tried to fix the problem in the last commit.

**Comment by marcoredz** [comment]
Yes! I confirm to you that now it works properly.

Thank you very much
