### ISSUE TITLE
IconButton accepting color?

### ISSUE THREAD

**Issue by calvintam236** [adrianos42/desktop#5]
I need it to change icon button color? Probably this should also applies to other buttons?

**Comment by adrianos42** [comment]
I need to see if it would make sense, since changing the color of the icon will impact the hover and highlight colors. That's why the only way now to change the color would be with a `ButtonThemeData`. If accepting color as an argument, then I would need to see how the the other colors would behave when the user pressed the button and so on.

**Comment by adrianos42** [comment]
Also, for example, if I change the color of the icon or any other button, and happens that it's the same color as the default hover color, then there would be no difference in color when hovering it. Another option I would consider is adding a color parameter but then calculating it to change saturation and lightness, as to have different colors according to different gestures.

**Comment by calvintam236** [comment]
Material version accepts `color`, `disabledColor`, `focusColor`, `splashColor`, `highlightColor` and `hoverColor`. For my case, I need color for differentiating primary and secondary buttons.

Ref: https://api.flutter.dev/flutter/material/IconButton-class.html

**Comment by adrianos42** [comment]
All the buttons accept color as parameter now. If you wanna change all the colors like `highlightColor` and `hoverColor`, then you will need to use `ButtonTheme`.

**Comment by calvintam236** [comment]
Can it accept `Color` instead of `HSLColor`?

**Comment by adrianos42** [comment]
Well, I cannot change the color representation in the entire library, since I've decided long ago to use HSL. You can still use `HSLColor.fromColor(color)` to convert from rgb.

**Comment by calvintam236** [comment]
I have tried `HSLColor.fromColor(color).withLightness(0.4)` for `color`, but it is a color close to dark gray. As we are unable to set`hoverColor`, the icon turns to white on hover.

Shouldn’t the `hoveredForeground`generated by the color inputed? Right now, it is not doing anything regards to the `color` param.

Ref: https://github.com/adrianos42/desktop/blob/18213ecab71cf8268ea7c04b93931c6af13a7a26/desktop/lib/src/desktop/input/button.dart#L202

**Comment by adrianos42** [comment]
I wanted to use white a standard for all buttons, even for `Tab` and `Tree`. So only the pressed color would be similar as the custom color. But you can just use a `ButtonTheme`, and change any color you want. This has been my intention, so you change only when really necessary, but then you'd need to change the theme for the button.

**Comment by adrianos42** [comment]
But it actually makes sense for the custom button to not have the hover color as white, since with the normal button it's only highlighting the gray color. I will change that, but I may also add some constraints about the color to be used, as not to be too light, too dark or having less saturation than required.

**Comment by adrianos42** [comment]
I've added option for passing `highlightColor` and `hoverColor` directly to `Button`, without need to use a theme data. The focus color will be the same as the hover color for now. This also applies to text and icon buttons. It's in the master branch, see if works fine.

**Comment by calvintam236** [comment]
I will test that soon. Right now, as I am using [sizer](https://pub.dev/packages/sizer) package and I need to have pass `size` into `Button.icon()` and `style` into `Button.text()` for responsive text/icon size?

**Comment by adrianos42** [comment]
Sure, but wouldn't it be better if you had a `ButtonThemeData` at the top of the tree with a responsive size for all buttons, instead of passing the size for each button? But anyways, guess both options make sense. The only problem would be with other buttons like checkbox, since they don't have a parameter for size yet.

**Comment by calvintam236** [comment]
> Sure, but wouldn't it be better if you had a `ButtonThemeData` at the top of the tree with a responsive size for all buttons, instead of passing the size for each button? But anyways, guess both options make sense. The only problem would be with other buttons like checkbox, since they don't have a parameter for size yet.

Material’s checkbox has a `width` constant set to `18`. Since `desktop` is not material, maybe this default value can change by parameter.

Ref: https://api.flutter.dev/flutter/material/Checkbox/width-constant.html

**Comment by calvintam236** [comment]
> I've added option for passing `highlightColor` and `hoverColor` directly to `Button`, without need to use a theme data. The focus color will be the same as the hover color for now. This also applies to text and icon buttons. It's in the master branch, see if works fine.

Can you do a pre-release version on pub.dev? I am having some issues using git url in pubspec?

**Comment by adrianos42** [comment]
I can only do this tomorrow, since it's a bit complicated because how the button will behave with a different size.

**Comment by adrianos42** [comment]
I've created a prerelease in pub.dev. I've jumped to version 3.0.0 since I'll try to make this one more stable, and with this some break changes, not only new features and bug fixes. See `3.0.0-dev.1`.

**Comment by calvintam236** [comment]
> I've created a prerelease in pub.dev. I've jumped to version 3.0.0 since I'll try to make this one more stable, and with this some break changes, not only new features and bug fixes. See `3.0.0-dev.1`.

Getting this error: `desktop-3.0.0-dev.1/lib/src/desktop/app.dart:253:24: Error: 'ShortcutActivator' isn't a type.`

**Comment by adrianos42** [comment]
I guess you need to upgrade flutter. My current version requires this new class for shortcuts. I'm using the dev channel, don't know if the others are affected.

**Comment by calvintam236** [comment]
> I guess you need to upgrade flutter. My current version requires this new class for shortcuts. I'm using the dev channel, don't know if the others are affected.

I’m on v2.0.6. I have some packages that are not yet supporting for v2.2.

**Comment by adrianos42** [comment]
Which packages? Don't they have a prerelease?

**Comment by adrianos42** [comment]
By the way, the version 2.2.0 is already in the stable channel, but I don't know why the hell they introduce break changes in feature new versions.

**Comment by calvintam236** [comment]
> Which packages? Don't they have a prerelease?

I am using database package called realm, and there are other packages that are not even supporting null-safety..

**Comment by adrianos42** [comment]
I've removed the current flutter pre-release dependency. See `3.0.0-dev.2` in pubdev. This desktop `3.0` version will only depend on flutter `2.2` for a while, since it's already in stable channel. Maybe the next version.
