### ISSUE TITLE
Dialog backgroundColor or decoration?

### ISSUE THREAD

**Issue by calvintam236** [adrianos42/desktop#6]
Sorry for requesting again. I am trying to set `decoration` (or `backgroundColor`) on `Dialog`, but it looks like impossible in the current constructor.

This is what I want to do on my component - passing `BoxDecoration` to `Dialog`:
```dart
Container(
  decoration: BoxDecoration(
    gradient: LinearGradient(
      colors: [
        colorScheme['secondary']!,
        colorScheme['secondaryVariant']!,
      ],
    ),
  ),
  child: xxx,
),
```

**Comment by adrianos42** [comment]
I didn't understand what you meant. You can pretty much pass anything with a dialog:
```dart
showDialog(
  context: context,
  barrierDismissible: true,
  builder: (context) => Dialog(
    body: Container(),
    title: Text(''),
    menus: [],
  ),
)
```

**Comment by calvintam236** [comment]
`Dialog` code already has a `Container` just for padding. I would just like passing a `BoxDecoration` (`decoration`) into that `Container` instead of wrapping with another one (`dialogPadding` won’t work in current design so it has to set to `0` and add into this new `Container`).

**Comment by adrianos42** [comment]
You don't need to use the `Dialog` widget in `showDialog` necessary, you can use anything really. The `builder` just uses a `WidgetBuilder`. The only problem here is that you'll need to use a column to create the title and buttons. Otherwise, it is not the point for `Dialog` to have a custom decoration, only the background color, title, body, and menu.

**Comment by calvintam236** [comment]
Right now, I am using `showDialog()` to open the component `Drawer`, which is the same code at the issue. As I am using `beamer`, and I want no transition on route change by [doing this](https://github.com/slovnicki/beamer/issues/234#issuecomment-830575971), it will get the error screen above at the following steps:
1. run `showDialog()`
2. `beamToNamed(‘page 1’)`
3. `beamToNamed(‘page 2’)`
4. `beamToNamed(‘page 1’)` => error

**Comment by adrianos42** [comment]
The `showDialog` function uses the root `Navigator`, wouldn't this be the problem? But I will need to do some testings with `beamer` to see how it using the `Navigator`.

**Comment by adrianos42** [comment]
```dart
return Navigator.of(context, rootNavigator: true).push<T>(createDialogRoute(
    builder: builder,
    context: context,
    barrierDismissible: barrierDismissible,
    filter: filter,
    barrierColor: barrierColor,
  ));
```
This is basically the function, wouldn't it be different with `beamer`?

**Comment by calvintam236** [comment]
https://github.com/slovnicki/beamer/search?l=Dart&q=Navigator

I don’t find any `Navigator` keyword in `beamer` (not directly using `Navigator`?).
